#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Define ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to check if command succeeded
check_command() {
  if [ $? -eq 0 ]; then
    echo "${GREEN}$1 succeeded${NC}"
  else
    echo "${RED}$1 failed${NC}"
  fi
}

# Running tests
echo -e "${YELLOW}Running tests...${NC}"
yarn test
check_command "Tests"

# Running linter
echo -e "${YELLOW}Running linter...${NC}"
yarn lint
check_command "Linting"
