#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Define ANSI color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Function to run a command and check its success
run_and_check() {
  echo -e "${YELLOW}Running $1...${NC}"
  if $2; then
    echo -e "\n${GREEN}$1 succeeded${NC}\n"
  else
    echo -e "\n${RED}$1 failed${NC}\n"
  fi
}

# Running tests
run_and_check "Tests" "yarn test"

# Running linter
run_and_check "Linter" "yarn lint"
